/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取 API 与依赖健康状态 */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/import/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建导入会话 */
        post: operations["createImportSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/import/sessions/{sessionId}/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 为上传对象签发预签名信息 */
        post: operations["createUploadTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/import/sessions/{sessionId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 确认上传结果并闭合导入状态机 */
        post: operations["confirmUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/discovery/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取按时间线排列的资产摘要 */
        get: operations["listTimelineAssets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
            traceId: string;
            details?: {
                [key: string]: unknown;
            };
        };
        CursorPageInfo: {
            nextCursor?: string;
            hasNextPage: boolean;
        };
        HealthCheck: {
            name: string;
            healthy: boolean;
            detail?: string;
            /** Format: date-time */
            checkedAt: string;
        };
        HealthResponse: {
            /** @enum {string} */
            status: "ok" | "degraded" | "failed";
            checks: components["schemas"]["HealthCheck"][];
        };
        CreateImportSessionRequest: {
            /** Format: uuid */
            libraryId: string;
            /** @enum {string} */
            source: "web-upload" | "desktop-batch" | "export-restore";
            expectedItemCount?: number;
            note?: string;
        };
        ImportSession: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            libraryId: string;
            /** @enum {string} */
            status: "draft" | "awaiting-upload" | "uploaded" | "confirmed" | "failed";
            source: string;
            /** Format: date-time */
            expiresAt: string;
        };
        CreateUploadTicketRequest: {
            fileName: string;
            contentType: string;
            contentLength: number;
            contentSha256?: string;
            /** @default false */
            multipart: boolean;
        };
        UploadTicket: {
            /** Format: uuid */
            sessionId: string;
            objectKey: string;
            /** @enum {string} */
            method: "PUT" | "POST";
            /** Format: uri */
            url: string;
            headers?: {
                [key: string]: string;
            };
            formFields?: {
                [key: string]: string;
            };
            /** Format: date-time */
            expiresAt: string;
            checksumAlgorithm?: string;
        };
        ConfirmUploadRequest: {
            objectKey: string;
            contentLength: number;
            etag?: string;
            contentSha256?: string;
        };
        AssetAcceptedResponse: {
            /** Format: uuid */
            assetId: string;
            /** Format: uuid */
            importSessionId: string;
            /** @enum {string} */
            processingStage: "accepted" | "stored" | "derivatives-ready" | "metadata-ready" | "ai-ready" | "indexed" | "partial-failure";
        };
        AssetSummary: {
            /** Format: uuid */
            assetId: string;
            mediaType: string;
            /** Format: date-time */
            timelineTimestamp: string;
            processingStage: string;
            backupStatus: string;
            thumbnailToken?: string;
            captionPreview?: string;
        };
        TimelineResponse: {
            items: components["schemas"]["AssetSummary"][];
            pageInfo: components["schemas"]["CursorPageInfo"];
        };
    };
    responses: {
        /** @description 标准错误响应 */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        SessionId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 健康检查结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    createImportSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateImportSessionRequest"];
            };
        };
        responses: {
            /** @description 导入会话已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportSession"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    createUploadTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUploadTicketRequest"];
            };
        };
        responses: {
            /** @description 上传凭据已签发 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadTicket"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    confirmUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmUploadRequest"];
            };
        };
        responses: {
            /** @description 上传已确认并开始后续处理 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetAcceptedResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    listTimelineAssets: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 时间线结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
}
